---

version: 1
update_configs:
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          update_type: all
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.14"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.15"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.16"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.17"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.18"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.19"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.20"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.21"
    allowed_updates:
      - match:
          update_type: security
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    target_branch: "3.22"
    allowed_updates:
      - match:
          update_type: security
